server:
  port: 8093
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 5000
    lettuce:
      pool:
        max-idle: 150
        min-idle: 5
        max-active: 150
        max-wait: 10000

